backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "Startseite"
    name: "startseite"
    files:
      - label: "Hauptbanner"
        name: "banner"
        file: "data/de/homepage.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: Hauptbanner
            name: banner
            widget: object
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Text, name: title2, widget: text}
              - {label: Bild, name: bg_image, widget: image}
              - {label: Bild, name: brandImage, widget: image}
              - {label: Text, name: content, widget: text}
  