backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "/images"
collections:
  - label: "Deutsch (de)"
    name: "deutsch"
    files:
      - label: "Startseite (de)"
        name: "startseiteDE"
        file: "data/de/homepage.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: "Hauptbanner"
            name: banner
            widget: object
            collapsed: true
            fields:
              - {label: Hintergrundbild, name: bg_image, widget: image}
              - {label: Titel, name: title, widget: string}
              - {label: Titel, name: title2, widget: text}
              - {label: Logo, name: brandImage, widget: image}
              - {label: Text, name: content, widget: text}
              - label: "Newsletter"
                name: button_solid
                widget: object
                collapsed: true
                fields:
                   - {label: Newsletter abonieren, name: enabled, widget: boolean}
          - label: "Unsere Exklusivmarken"
            name: ourBrands
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: title, widget: string}
               - {label: Text, name: content, widget: text}
               - label: Marken
                 name: brand_items
                 widget: list
                 fields:
                    - {label: Name, name: label, widget: string}
                    - {label: Bild, name: image, widget: image}
                    
          - label: "Texbanner 1"
            name: textbanner1
            widget: object
            collapsed: true
            fields:
               - {label: Titel, name: title, widget: string}  
               - {label: Text, name: text, widget: text}
               - {label: Hintergrundbild, name: background, widget: image} 
               - {label: Farbe, name: color, widget: color}
               - {label: Ausrichtung(aktiviert:links  deaktiviert:rechts), name: align_left, widget: boolean}
          - label: "Produkte"
            name: Products
            widget: object
            collapsed: true
            fields:
               - label: Unsere Produkte
                 name: categories
                 widget: list
                 fields:
                    - {label: Name, name: name, widget: string}
                    - {label: Artikelbeschreibung, name: description, widget: text}
                    - {label: Artikel ist neu(wird markiert), name: isnew, widget: boolean}
                    - {label: Bild, name: image, widget: image}
                    - {label: Link zum Shop, name: link, widget: string}
          - label: "Produktkategorien"
            name: ProductCategories
            widget: object
            collapsed: true
            fields:
               
               - label: Kategorien
                 name: categories
                 widget: list
                 fields:
                    - {label: Name, name: name, widget: string}
                    - {label: Link, name: link, widget: string}
                    - {label: Beschreibung, name: description, widget: text}
                    - {label: Bild, name: image, widget: image}
                    - {label: Buttonfarbe, name: btnColor, widget: color}
          - label: "Service"
            name: service
            widget: object
            collapsed: true
            fields:
               - {label: Servicebeschreibung, name: title, widget: string}
               - label: Kategorien
                 name: service_item
                 widget: list
                 fields:
                    - {label: Bereich, name: title, widget: string}
                    - {label: Bild, name: logo, widget: image}
                    - {label: Beschreibung, name: content, widget: text}
                    
          - label: "Texbanner 2"
            name: textbanner2
            widget: object
            collapsed: true
            fields:
               - {label: Titel, name: title, widget: string}  
               - {label: Text, name: text, widget: text}
               - {label: Hintergrundbild, name: background, widget: image} 
               - {label: Farbe, name: color, widget: color}
               - {label: Ausrichtung(aktiviert:rechts  deaktiviert:links), name: align_left, widget: boolean}
          - label: "Download"
            name: downloads
            widget: object
            collapsed: true
            fields:
               - label: Download
                 name: download
                 widget: list
                 fields:
                    - {label: Bereich, name: title, widget: string}
                    - {label: Bild, name: image, widget: image}
                    - {label: Beschreibung, name: content, widget: text}
                    - {label: Downloadlink, name: link, widget: string}
          - label: "Newsletter"
            name: newsletter
            widget: object
            collapsed: true
            fields:
               - {label: Titel, name: title, widget: string}
               - {label: Text Newsletteranmeldung, name: why, widget: text}
               - {label: Text Beschreibung, name: instructions, widget: text}
          - label: "Statistiken"
            name: statistics
            widget: object
            collapsed: true
            fields:
               - {label: Titel, name: title, widget: string}
               - {label: Titel, name: subtitle, widget: string}
               - label: Kategorien
                 name: categories
                 widget: list
                 fields:
                    - {label: Bereich, name: title, widget: string}
                    - {label: Farbe, name: color, widget: Color}
                    - {label: Beschreibung, name: text, widget: text}
                    - {label: Name, name: name, widget: string}
          - label: "Standards"
            name: standards
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
               
  - label: "English (en)"
    name: "english"
    files:
      - label: "Startseite (en)"
        name: "startseiteEN"
        file: "data/en/homepage.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: "Hauptbanner"
            name: banner
            widget: object
            collapsed: true
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Text, name: title2, widget: text}
              - {label: Bild, name: bg_image, widget: image}
              - {label: Bild, name: brandImage, widget: image}
              - {label: Text, name: content, widget: text}
          - label: "Unsere Exklusivmarken"
            name: ourBrands
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Texbanner 1"
            name: textbanner1
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}   
          - label: "Produkte"
            name: products
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Produktkatgorien"
            name: ProductCategories
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Service"
            name: service
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Textbanner 2"
            name: textbanner2
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Downnloads"
            name: downloads
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Newsletter"
            name: newsletter
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Statistiken"
            name: statistics
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
          - label: "Standards"
            name: standards
            widget: object
            collapsed: true
            fields:
               - {label: Name, name: content, widget: string}
                                                              
      
              
       
        
                   

      
                                                                 
      
              
       
        
                   

      
    
                 
              
                
                   
                   
               