backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "English"
    name: "english"
    folder: "content/english/about"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Background", name: "bg_image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Bodytext", name: "body", widget: "markdown"}
  


      
      
         
      
                       
          
                            
      
         
        
