backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "data/de/about.yml"
        fields:
          - {label: Title, name: about/title, widget: string}
          - {label: Textfeld, name: about/text, widget: markdown}
          
          
          
      
  


      
      
         
      
                       
          
                            
      
         
        
