backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about-de"
        file: "data/de/about.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: Über Uns
            name: about
            widget: list
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Text, name: text, widget: string}
              - {label: Bild, name: url, widget: image}
          
          
          
          
      
  


      
      
         
      
                       
          
                            
      
         
        
