backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About-DE"
        name: "about"
        file: "data/de/about.yml"
        - label: About Deutsch
            name: überUns
            widget: list
            fields:
              - {label: Titel, name: title, widget: string}
              - {label: Text, name: text, widget: string}
              - {label: Team, name: url, widget: image}
          
          
          
      
  


      
      
         
      
                       
          
                            
      
         
        
