backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "data/de/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: object
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Position, name: text, widget: string}
              - {label: Photo, name: url, widget: image}
        
          
          
          
          
      
  


      
      
         
      
                       
          
                            
      
         
        
