backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "Über Uns (DE,EN,FR,IT)"
    name: "about"
    files:
      - label: "About DE"
        name: "aboutDE"
        file: "data/de/about.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: Über Uns
            name: about
            widget: object
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Bild, name: url, widget: image}
      - label: "About EN"
        name: "aboutEN"
        file: "data/en/about.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: About Us
            name: about
            widget: object
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Picture, name: url, widget: image}
      - label: "About FR"
        name: "aboutFR"
        file: "data/fr/about.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: À propos de nous
            name: about
            widget: object
            fields:
              - {label: le nom, name: title, widget: string}
              - {label: texte, name: text, widget: text}
              - {label: Image, name: url, widget: image}
      - label: "About IT"
        name: "aboutIT"
        file: "data/it/about.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: su noi
            name: about
            widget: object
            fields:
              - {label: Nome, name: title, widget: string}
              - {label: il testo, name: text, widget: text}
              - {label: immagine, name: url, widget: image}
  - label: "Philosophie (DE,EN,FR,IT)"
    name: "phil"
    files:
      - label: "Philosophie DE"
        name: "philDE"
        file: "data/de/about.yml"
        extension: "yml"
        format: "yml"
        fields:
          - label: "Philosophie"
            name: "philosophy"
            widget: object
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Text, name: content, widget: text}
              - {label: Bild, name: img, widget: image}              
                                 

  
        
          
          
          
          
      
  


      
      
         
      
                       
          
                            
      
         
        
    
  
  
