backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "static/images"
collections:
  - label: "Definitionen"
    name: "definitionen"
    folder: "content/german/about"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Bild", name: "bg_image", widget: "image"}
      - {label: "Beschreibung", name: "description", widget: "string"}
      - {label: "Seitentext", name: "body", widget: "markdown"}
  - label: "Impressum"
    name: "impressum"
    folder: "content/german/brands"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "date"}
      - {label: "Beschreibung", name: "description", widget: "string"}
      - {label: "Seitentext", name: "aliases", widget: "object"}
  - label: "Regeln-Fallstricke"
    name: "regeln-fallstricke"
    folder: "content/german/contact"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "date"}
      - {label: "Beschreibung", name: "description", widget: "string"}
      - {label: "Seitentext", name: "body", widget: "markdown"}